# Generated by Django 2.1.1 on 2018-10-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=10)),
                ('area_name_reg', models.CharField(max_length=10)),
                ('area_name_short', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DisList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='InfeDis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=10)),
                ('dis_name', models.CharField(max_length=60)),
                ('case_num', models.IntegerField()),
                ('death_num', models.IntegerField()),
                ('ici_rate', models.FloatField()),
                ('mort_rate', models.FloatField()),
            ],
        ),
    ]
