# Generated by Django 2.1.1 on 2018-11-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agg_id', models.CharField(max_length=50)),
                ('ag_g', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AggTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=50)),
                ('reg_id', models.CharField(max_length=50)),
                ('dis_id', models.CharField(max_length=50)),
                ('agg_id', models.CharField(max_length=50)),
                ('gd_id', models.CharField(max_length=50)),
                ('case_num', models.IntegerField()),
                ('dea_num', models.IntegerField()),
                ('inci_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('mort_rate', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DisCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_id', models.CharField(max_length=50)),
                ('dis_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GdCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gd_id', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MonthCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('month_cn', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=50)),
                ('pro_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=50)),
                ('reg_id', models.CharField(max_length=50)),
                ('dis_name', models.CharField(max_length=50)),
                ('pro_name', models.CharField(max_length=50)),
                ('case_num', models.IntegerField()),
                ('dea_num', models.IntegerField()),
                ('inci_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('mort_rate', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RegCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_id', models.CharField(max_length=50)),
                ('reg_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=50)),
                ('reg_id', models.CharField(max_length=50)),
                ('disease', models.CharField(max_length=50)),
                ('case_num', models.IntegerField()),
                ('dea_num', models.IntegerField()),
                ('inci_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('mort_rate', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
