# Generated by Django 2.1.1 on 2018-11-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dis_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggtb',
            name='agg_id',
            field=models.ForeignKey(on_delete='SET_NULL', to='dis_dashboard.AggCode', to_field='agg_id'),
        ),
        migrations.AlterField(
            model_name='aggtb',
            name='dis_id',
            field=models.ForeignKey(on_delete='SET_NULL', to='dis_dashboard.DisCode', to_field='dis_id'),
        ),
        migrations.AlterField(
            model_name='aggtb',
            name='gd_id',
            field=models.ForeignKey(on_delete='SET_NULL', to='dis_dashboard.GdCode', to_field='gd_id'),
        ),
        migrations.AlterField(
            model_name='aggtb',
            name='month',
            field=models.ForeignKey(on_delete='SET_NULL', to='dis_dashboard.MonthCode', to_field='month'),
        ),
        migrations.AlterField(
            model_name='aggtb',
            name='reg_id',
            field=models.ForeignKey(on_delete='SET_NULL', to='dis_dashboard.RegCode', to_field='reg_id'),
        ),
        migrations.AlterField(
            model_name='protb',
            name='dis_id',
            field=models.ForeignKey(on_delete='SET_NULL', to='dis_dashboard.DisCode', to_field='dis_id'),
        ),
        migrations.AlterField(
            model_name='protb',
            name='month',
            field=models.ForeignKey(on_delete='SET_NULL', to='dis_dashboard.MonthCode', to_field='month'),
        ),
        migrations.AlterField(
            model_name='protb',
            name='pro_name',
            field=models.ForeignKey(on_delete='SET_NULL', to='dis_dashboard.ProCode', to_field='pro_name'),
        ),
        migrations.AlterField(
            model_name='protb',
            name='reg_id',
            field=models.ForeignKey(on_delete='SET_NULL', to='dis_dashboard.RegCode', to_field='reg_id'),
        ),
        migrations.AlterField(
            model_name='regtb',
            name='dis_id',
            field=models.ForeignKey(on_delete='SET_NULL', to='dis_dashboard.DisCode', to_field='dis_id'),
        ),
        migrations.AlterField(
            model_name='regtb',
            name='month',
            field=models.ForeignKey(on_delete='SET_NULL', to='dis_dashboard.MonthCode', to_field='month'),
        ),
        migrations.AlterField(
            model_name='regtb',
            name='reg_id',
            field=models.ForeignKey(on_delete='SET_NULL', to='dis_dashboard.RegCode', to_field='reg_id'),
        ),
    ]
