# Generated by Django 2.1.1 on 2018-11-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dis_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthcode',
            name='month',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
