# Generated by Django 2.1.1 on 2018-10-29 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dis_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfeDis',
            new_name='InfDis',
        ),
    ]
