# Generated by Django 2.1.1 on 2018-11-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dis_dashboard', '0002_auto_20181103_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regcode',
            name='id',
        ),
        migrations.AlterField(
            model_name='aggtb',
            name='reg_id',
            field=models.ForeignKey(on_delete='SET_NULL', to='dis_dashboard.RegCode'),
        ),
        migrations.AlterField(
            model_name='regcode',
            name='reg_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
