# Generated by Django 2.1.1 on 2018-11-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dis_dashboard', '0002_auto_20181103_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procode',
            name='pro_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='regcode',
            name='reg_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
