# Generated by Django 2.1.1 on 2018-11-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dis_dashboard', '0002_auto_20181103_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='regcode',
            name='reg_name_crct',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
