# Generated by Django 2.1.1 on 2018-11-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dis_dashboard', '0003_auto_20181103_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggtb',
            name='month',
            field=models.CharField(max_length=50),
        ),
    ]
