# Generated by Django 2.1.1 on 2018-11-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dis_dashboard', '0003_regcode_reg_name_crct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regcode',
            old_name='reg_name_crct',
            new_name='reg_name_crt',
        ),
    ]
