# Generated by Django 2.1.1 on 2018-11-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dis_dashboard', '0004_auto_20181104_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggcode',
            name='ag_g_ctr',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
