# Generated by Django 2.1.1 on 2018-11-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dis_dashboard', '0005_aggcode_ag_g_ctr'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggcode',
            name='ag_g_p5',
            field=models.CharField(default='', max_length=50),
        ),
    ]
