# Generated by Django 2.1.1 on 2018-11-05 07:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dis_dashboard', '0006_aggcode_ag_g_p5'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceBorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('popname', models.CharField(max_length=24)),
                ('code', models.CharField(max_length=12)),
                ('type', models.BigIntegerField()),
                ('display', models.BigIntegerField()),
                ('extention', models.IntegerField()),
                ('update', models.CharField(max_length=8)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('py', models.CharField(max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
