# Generated by Django 2.1.1 on 2018-11-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dis_dashboard', '0007_provinceborder'),
    ]

    operations = [
        migrations.AddField(
            model_name='regcode',
            name='admin_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
