# Generated by Django 2.1.1 on 2018-11-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dis_dashboard', '0008_regcode_admin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provinceborder',
            name='extention',
        ),
        migrations.RemoveField(
            model_name='provinceborder',
            name='update',
        ),
        migrations.AddField(
            model_name='provinceborder',
            name='reg_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='provinceborder',
            name='py',
            field=models.CharField(max_length=50),
        ),
    ]
