# Generated by Django 2.1.1 on 2018-10-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('invite_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
